### ISSUE TITLE
许多didi依赖包无法下载

### ISSUE THREAD

**Issue by YSRE** [didi/LogiEM#1]
io.github.zqrferrari:logi-elasticsearch-client:1.0.7 已经没有这个项目
org.elasticsearch » elasticsearch:2.3.3-SNAPSHOT 没有这个jar包
elasticsearch-didi:2.3.3-SNAPSHOT 没有这个jar包
还有很多包,应该是放在滴滴私库里了.外面没法编译

**Comment by linyunanit** [comment]
相关的jar包依赖已经整改过一版，辛苦pull最新的代码，重新编译试试。

**Comment by linyunanit** [comment]
> io.github.zqrferrari:logi-elasticsearch-client:1.0.7 已经没有这个项目 org.elasticsearch » elasticsearch:2.3.3-SNAPSHOT 没有这个jar包 elasticsearch-didi:2.3.3-SNAPSHOT 没有这个jar包 还有很多包,应该是放在滴滴私库里了.外面没法编译

依赖滴滴内部的jar包已经整改过一版，辛苦pull最新的代码，重新编译试试。
如果还是找不到elasticsearch:2.3.3-SNAPSHOT ，可以在中央仓库下载  https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch/2.3.3

**Comment by huafeisuperman** [comment]
已经修复了，可以重新更新下再试试
