### ISSUE TITLE
开源版本完全没有体现产品的核心优势

### ISSUE THREAD

**Issue by zhangJingTao** [didi/LogiEM#2]
花了几个小时搭建起来后发现，绝大部分亮点功能都是商业版本才有。

目前开源的功能并没有解决大家的痛点。

现有功能，基本上用Cerebro就可以替代。一些常用操作成了商业功能。

比如README中提到的产品优势。基本上开源版本没有这种优势...

一个超级阉割版本的控制台，不如不存在。

这种开源形式...真的一言难尽

作者换位思考下，会有人用开源版本吗？

**Comment by zhangliangboy** [comment]
首先感谢你的反馈，一则很多功能还在迭代规划的路上，二则我们遵循少即是多的原则，1.0/2.0 都还会关注在围绕ES引擎基于指标和日志的可观测性上，3.0预计会关注在基于Agent存量集群运维自助化以及日常高频操作例如索引迁移、重建等高频运维操作的平台化上，后续会进一步关注在专家经验诊断能力的产品化上，三则 开源我们是认真和严肃的，正因如此我们一直没有官方宣传，目前还是在Beta版本阶段

其次我们的商业特性，一旦跟引擎的改造相关，就不准备开源，毕竟我们内部版本的ES改造是不计划开源的，且后续ES 7.10版本之后，Licence也变更了 

最后，你觉得那些商业特性可以摆脱引擎改造的特性，可以直接反馈给我们，感谢你来自社区的反馈
